name: Build Repo1

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v4

      - name: Simulate build
        run: |
          echo "Building Repo1..."
          sleep 2
          echo "Build complete"


  trigger-tests:
    needs: build
    uses: laditya2805/MySampleUAT/.github/workflows/run-tests.yaml@main
    with: {}
